/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nEW u
 */
public class Dash extends javax.swing.JFrame {

    
    DefaultTableModel df;
    public Dash() {
        
        initComponents();
        panelfront.setFocusable(true);
        
        DefaultListModel di = new DefaultListModel();
        di.addElement("1. AES");
        di.addElement("2. Triple DES");
        di.addElement("3. TWO FISH");
        di.addElement("4. RSA");
        di.addElement("5. DES");
        
        list1.add("1. AES");
        list1.add("2. Triple DES");
        list1.add("3. BLOWFISH");
        list1.add("4. RSA");
        list1.add("5. DES");
        Font f=new Font(Font.MONOSPACED,  Font.BOLD, 44);
        list1.setFont(f);
    }

/**
     * Creates new form Dash
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Algooptios = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jLabel14 = new javax.swing.JLabel();
        panelfront = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField_browse = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_inkey = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Algooptios.setBackground(new java.awt.Color(0, 33, 78));
        Algooptios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/newpackage/Images/icons8_question_shield_60px_2.png"))); // NOI18N

        list1.setBackground(new java.awt.Color(0, 33, 78));
        list1.setFont(new java.awt.Font("Harrington", 3, 36)); // NOI18N
        list1.setForeground(new java.awt.Color(240, 240, 240));
        list1.setName("ALGORITHMS"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/newpackage/Images/icons8_menu_filled_50px.png"))); // NOI18N
        jLabel14.setText(" ALGORITHM");
        jLabel14.setToolTipText("");

        panelfront.setBackground(new java.awt.Color(112, 193, 232));
        panelfront.setForeground(new java.awt.Color(0, 51, 51));

        jButton1.setBackground(new java.awt.Color(0, 33, 78));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/newpackage/Images/icons8_external_link_50px.png"))); // NOI18N
        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField_browse.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jTextField_browse.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_browse.setText("File to perform...");
        jTextField_browse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_browseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_browseFocusLost(evt);
            }
        });
        jTextField_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_browseActionPerformed(evt);
            }
        });

        jProgressBar1.setForeground(new java.awt.Color(204, 204, 204));
        jProgressBar1.setStringPainted(true);

        jButton2.setBackground(new java.awt.Color(0, 33, 78));
        jButton2.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/newpackage/Images/icons8_lock_filled_50px_1_1.png"))); // NOI18N
        jButton2.setText("ENCRPYT");
        jButton2.setAlignmentX(0.5F);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 33, 78));
        jButton3.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/newpackage/Images/icons8_unlock_filled_50px_1.png"))); // NOI18N
        jButton3.setText("DECRYPT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setFont(new java.awt.Font("Pristina", 0, 80)); // NOI18N
        jLabel8.setText("DataCrypto5");

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/newpackage/Images/icons8_key_50px.png"))); // NOI18N
        jLabel9.setText("CIPHER KEY");

        jTextField_inkey.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jTextField_inkey.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_inkey.setText("Insert Key..");
        jTextField_inkey.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_inkeyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_inkeyFocusLost(evt);
            }
        });
        jTextField_inkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_inkeyActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(0, 33, 78));
        jTable1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr.No", "File Name", "Algorithm used", "Date and Time", "Status"
            }
        ));
        jTable1.setAutoscrolls(false);
        jTable1.setGridColor(new java.awt.Color(0, 51, 102));
        jScrollPane3.setViewportView(jTable1);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/newpackage/Images/icons8_security_checked_50px.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/newpackage/Images/002-data-1.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/newpackage/Images/data (1).png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("File cryption processing..");

        javax.swing.GroupLayout panelfrontLayout = new javax.swing.GroupLayout(panelfront);
        panelfront.setLayout(panelfrontLayout);
        panelfrontLayout.setHorizontalGroup(
            panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfrontLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(56, 56, 56)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addGap(113, 113, 113))
            .addGroup(panelfrontLayout.createSequentialGroup()
                .addGroup(panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelfrontLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel9))
                        .addGap(40, 40, 40)
                        .addGroup(panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_inkey, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelfrontLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(962, 962, 962)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelfrontLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelfrontLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addGroup(panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfrontLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfrontLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfrontLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(496, 496, 496))))
        );
        panelfrontLayout.setVerticalGroup(
            panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfrontLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_browse))
                .addGap(19, 19, 19)
                .addGroup(panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jTextField_inkey))
                .addGroup(panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelfrontLayout.createSequentialGroup()
                        .addGroup(panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelfrontLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(panelfrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton2))
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfrontLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelfrontLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfrontLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout AlgooptiosLayout = new javax.swing.GroupLayout(Algooptios);
        Algooptios.setLayout(AlgooptiosLayout);
        AlgooptiosLayout.setHorizontalGroup(
            AlgooptiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlgooptiosLayout.createSequentialGroup()
                .addGroup(AlgooptiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlgooptiosLayout.createSequentialGroup()
                        .addGroup(AlgooptiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AlgooptiosLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel14))
                            .addGroup(AlgooptiosLayout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel11)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlgooptiosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelfront, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AlgooptiosLayout.setVerticalGroup(
            AlgooptiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlgooptiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelfront, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Algooptios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Algooptios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser();
        j.showOpenDialog(null);
        File f = j.getSelectedFile();
        jTextField_browse.setText(f.getAbsolutePath());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_browseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_browseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x=list1.getSelectedIndex();
        switch(x){
            case 0:
                jTextArea1.setText("SELECTED 1");
                
                jProgressBar1.setValue(50);
                jProgressBar1.setForeground(Color.darkGray);
                df = (DefaultTableModel) jTable1.getModel();
                df.addRow(new Object[]{"1","abc.txt","AES","20-apr-2019"});
                
                
                break;
            case 1:
                jTextArea1.setText("SELECTED 2");
                jProgressBar1.setValue(60);
                jProgressBar1.setForeground(Color.darkGray);
                df = (DefaultTableModel) jTable1.getModel();
                df.addRow(new Object[]{"2","abc.txt","Triple DES","20-apr-2019"});
                break;
            case 2:
                jTextArea1.setText("SELECTED 3");
                break;
            case 3:
                jTextArea1.setText("SELECTED 4");
                break;
            case 4:
                jTextArea1.setText("SELECTED 5");
                break;
            default:
                jTextArea1.setText("Wrong choice please select correct option..");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        int x=list1.getSelectedIndex();
        switch(x){
            case 0:
                jTextArea1.setText("SELECTED 1");
                break;
            case 1:
                jTextArea1.setText("SELECTED 2");
                break;
            case 2:
                jTextArea1.setText("SELECTED 3");
                break;
            case 3:
                jTextArea1.setText("SELECTED 4");
                break;
            case 4:
                jTextArea1.setText("SELECTED 5");
                break;
            default:
                jTextArea1.setText("Wrong choice please select correct option..");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField_inkeyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_inkeyFocusGained
if(jTextField_inkey.getText().equals("Insert Key..")){
jTextField_inkey.setText("");
}
jTextField_inkey.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jTextField_inkeyFocusGained

    private void jTextField_inkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_inkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_inkeyActionPerformed

    private void jTextField_inkeyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_inkeyFocusLost
        if(jTextField_inkey.getText().equals("")){
jTextField_inkey.setText("Insert Key..");
}
jTextField_inkey.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jTextField_inkeyFocusLost

    private void jTextField_browseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_browseFocusGained
if(jTextField_browse.getText().equals("File to perform...")){
jTextField_browse.setText("");
}
jTextField_browse.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jTextField_browseFocusGained

    private void jTextField_browseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_browseFocusLost
if(jTextField_browse.getText().equals("")){
jTextField_browse.setText("File to perform...");
}
jTextField_browse.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jTextField_browseFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Algooptios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_browse;
    private javax.swing.JTextField jTextField_inkey;
    private java.awt.List list1;
    private javax.swing.JPanel panelfront;
    // End of variables declaration//GEN-END:variables

    private Color Color(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
